"""One committed snapshot of the public API surface, diffed on every run — the first U-5 ratchet.

The contract and the capability declarations are each guarded today (``tests/test_contract_names.py``,
``tests/base/test_capabilities.py``, ``tests/test_package_exports.py``), but each holds its own slice against an
``EXPECTED`` list written inline in that test. This is the **consolidated** guard: the whole engine-free public
surface — top-level exports, the Core/Tier-2 contract (names, keywords, call shape), what keywords each backend
honours, and each tier's full :class:`~digitalearth.base.capabilities.Capabilities` — captured in one committed
artifact (:data:`SNAPSHOT_PATH`) and compared as one unit. Any addition, removal, rename, keyword change or
capability change anywhere in that surface shows up as a single reviewable diff in the pull request, so a public
change is a deliberate, reviewed snapshot update rather than something that slips through unnoticed.

**It is engine-free on purpose.** Every source it reads — ``digitalearth.__all__``, ``base.contract``,
``api.BACKEND_CAPABILITIES`` and each tier's ``capabilities.CAPABILITIES`` — imports without MapLibre, HoloViz or
PyVista, so this runs (and ratchets) in the lean ``dev`` matrix on every OS, not only where an extra is installed.

**To change the API on purpose:** make the change, run ``python tests/test_api_snapshot.py`` to rewrite
:data:`SNAPSHOT_PATH`, and commit the diff alongside the change. An *unintended* drift fails the test with the
diff inline.
"""

import difflib
import importlib
import json
from pathlib import Path
from typing import Any, Dict

from digitalearth import __all__ as TOP_LEVEL_EXPORTS
from digitalearth.api import BACKEND_CAPABILITIES
from digitalearth.base import contract

#: The committed snapshot, beside this test. Regenerated by running this file as a script.
SNAPSHOT_PATH = Path(__file__).with_name("api_snapshot.json")

#: Backend name → the module holding that tier's ``CAPABILITIES`` value. All four import engine-free.
_TIER_CAPABILITY_MODULES = {
    "matplotlib": "digitalearth.static.capabilities",
    "web": "digitalearth.web.capabilities",
    "interactive": "digitalearth.interactive.capabilities",
    "3d": "digitalearth.three_d.capabilities",
}


def _method(method: contract.Method) -> Dict[str, Any]:
    """Reduce one contract :class:`~digitalearth.base.contract.Method` to its snapshot form.

    Args:
        method: The contract method.

    Returns:
        Its name, sorted keywords, return kind, and declared call shape — the call surface a caller sees.
    """
    return {
        "name": method.name,
        "keywords": sorted(method.keywords),
        "returns": method.returns,
        "first_argument": method.first_argument,
        "sequence_order": list(method.sequence_order)
        if method.sequence_order
        else None,
        "builds_in": method.builds_in,
    }


def _tier_capabilities(backend: str) -> Dict[str, Any]:
    """Return one tier's full declared capabilities, read engine-free from its ``capabilities`` module.

    Args:
        backend: The backend name (a key of :data:`_TIER_CAPABILITY_MODULES`).

    Returns:
        The tier's :meth:`~digitalearth.base.capabilities.Capabilities.to_dict`.
    """
    module = importlib.import_module(_TIER_CAPABILITY_MODULES[backend])
    return module.CAPABILITIES.to_dict()


def public_api_surface() -> Dict[str, Any]:
    """Build the engine-free public API surface as plain, sorted, JSON-able data.

    Returns:
        The top-level exports, the Core/Tier-2 contract (in declaration order) and its ``PENDING`` table, the
        per-backend honoured keywords, and each tier's full capabilities — everything deterministic across runs
        and operating systems so two machines produce byte-identical output.
    """
    return {
        "top_level_exports": sorted(TOP_LEVEL_EXPORTS),
        "contract": {
            "core": [_method(method) for method in contract.CORE],
            "tier2": [_method(method) for method in contract.TIER2],
            "pending": {
                backend: dict(contract.PENDING[backend])
                for backend in sorted(contract.PENDING)
            },
        },
        "backend_keyword_capabilities": {
            backend: sorted(BACKEND_CAPABILITIES[backend])
            for backend in sorted(BACKEND_CAPABILITIES)
        },
        "backend_capabilities": {
            backend: _tier_capabilities(backend)
            for backend in sorted(_TIER_CAPABILITY_MODULES)
        },
    }


def _serialise(surface: Dict[str, Any]) -> str:
    """Serialise the surface deterministically (sorted keys, trailing newline), so a diff is stable."""
    return json.dumps(surface, indent=2, sort_keys=True) + "\n"


def test_the_public_api_matches_the_committed_snapshot():
    """The ratchet: the live public surface must equal the committed snapshot, or the diff is shown.

    Test scenario:
        Rebuild the surface from the live declarations and compare it, serialised, to the committed
        ``api_snapshot.json``. A match means nothing public moved; a mismatch is either an intended change
        whose snapshot was not regenerated, or an unintended public-API change — both of which a reviewer
        should see, so the failure carries the unified diff rather than an opaque "dicts differ".
    """
    current = _serialise(public_api_surface())
    committed = SNAPSHOT_PATH.read_text(encoding="utf-8")
    if current != committed:
        diff = "".join(
            difflib.unified_diff(
                committed.splitlines(keepends=True),
                current.splitlines(keepends=True),
                fromfile="tests/api_snapshot.json (committed)",
                tofile="the live public API",
            )
        )
        raise AssertionError(
            "the public API surface drifted from tests/api_snapshot.json. If the change is intended, "
            "regenerate it with `python tests/test_api_snapshot.py` and commit the diff; otherwise this is "
            f"an unintended public-API change.\n\n{diff}"
        )


if (
    __name__ == "__main__"
):  # regenerate the committed snapshot after a deliberate API change
    SNAPSHOT_PATH.write_text(_serialise(public_api_surface()), encoding="utf-8")
    print(f"wrote {SNAPSHOT_PATH}")
