"""Consolidate every accepted cross-tier deviation into one frozen allowlist, and ratchet it — the last U-5.

The conformance and renderer suites each hold a tier to a *drift table* of what it legitimately cannot do:
``NO_PORTABLE_CHANNELS``, ``CANNOT_HIDE_AT_BUILD`` and ``NO_PORTABLE_CLASSIFICATION`` in
``tests/base/test_map_conformance.py``, and ``UNDRAWN_KINDS`` in ``tests/base/test_renderer_conformance.py``.
Each is both-direction-guarded there, so a deviation cannot outlive the defect it excuses — but they sit in four
places, and no one list says "here is every accepted cross-tier difference".

This builds that list. :func:`collect_known_deviations` reads the four tables, :func:`render_allowlist` renders
them into one page (:data:`ALLOWLIST_PATH`), and the ratchet holds the committed page to it. So adding or
removing a deviation in any of the four tables shows up as a single reviewable diff in this one allowlist; the
tables stay the source of truth and the enforcement, and this is the consolidated view of them.

Engine-free (the tables import without MapLibre/HoloViz/PyVista), so it runs in the ``dev`` matrix. **To change
it on purpose:** change the table, run ``python -m tests.test_known_deviations`` to rewrite the page, and commit.
"""

import textwrap
from pathlib import Path
from typing import Dict, List

from tests.base.test_map_conformance import (
    CANNOT_HIDE_AT_BUILD,
    NO_PORTABLE_CHANNELS,
    NO_PORTABLE_CLASSIFICATION,
)
from tests.base.test_renderer_conformance import UNDRAWN_KINDS
from tests.ratchet import assert_matches_committed

#: The committed allowlist, beside this test. Regenerated by running this module.
ALLOWLIST_PATH = Path(__file__).with_name("known_deviations.md")

#: The tier→reason tables, as (category, table). ``UNDRAWN_KINDS`` is nested and handled separately.
_FLAT_TABLES = (
    ("no_portable_channels", NO_PORTABLE_CHANNELS),
    ("cannot_hide_at_build", CANNOT_HIDE_AT_BUILD),
    ("no_portable_classification", NO_PORTABLE_CLASSIFICATION),
)

#: Each category's heading and one-line description, in the order they appear on the page.
_CATEGORIES = (
    (
        "no_portable_channels",
        "No portable style channels",
        "The tier records a layer's style in its engine's own spelling rather than folding it into the "
        "declared channels, so a styled layer is fully described only for the tier that drew it.",
    ),
    (
        "cannot_hide_at_build",
        "Cannot build a layer already hidden",
        "`visible=False` at build time is not honoured; a layer on this tier is hidden with `set_visible()` "
        "after it is built.",
    ),
    (
        "no_portable_classification",
        "No portable classification",
        "The tier publishes no class edges for a classified layer, so a figure carries none and a legend "
        "cannot be reproduced from the description alone.",
    ),
    (
        "undrawn_kind",
        "Kinds kept but not drawn",
        "The tier's renderer keeps a layer of this kind but draws nothing from its description — a custom "
        "engine object held by reference rather than rebuilt.",
    ),
)


def collect_known_deviations() -> List[Dict[str, str]]:
    """Read the four drift tables into one normalised, sorted list of accepted deviations.

    Returns:
        One entry per accepted deviation — ``{category, backend, subject, reason}`` — sorted by category,
        backend then subject, so the rendered page is stable across runs and operating systems.
    """
    entries: List[Dict[str, str]] = []
    for category, table in _FLAT_TABLES:
        entries.extend(
            {"category": category, "backend": backend, "subject": "", "reason": reason}
            for backend, reason in table.items()
        )
    for backend, kinds in UNDRAWN_KINDS.items():
        entries.extend(
            {
                "category": "undrawn_kind",
                "backend": backend,
                "subject": kind,
                "reason": reason,
            }
            for kind, reason in kinds.items()
        )
    return sorted(
        entries,
        key=lambda entry: (entry["category"], entry["backend"], entry["subject"]),
    )


def _bullet(entry: Dict[str, str]) -> str:
    """Render one deviation as a wrapped markdown bullet (≤ 120 columns)."""
    label = (
        f"{entry['backend']} · `{entry['subject']}`"
        if entry["subject"]
        else entry["backend"]
    )
    return textwrap.fill(
        f"- **{label}** — {entry['reason']}",
        width=112,
        subsequent_indent="  ",
        break_long_words=False,
        break_on_hyphens=False,
    )


def render_allowlist() -> str:
    """Render the whole allowlist page from the live tables: a preamble, then a section per category.

    Returns:
        The markdown page. A category with no live deviation is skipped, so the page lists exactly what is
        accepted now; a new entry adds a bullet (or a section), a fixed one removes it — each a reviewable diff.
    """
    grouped: Dict[str, List[Dict[str, str]]] = {}
    for entry in collect_known_deviations():
        grouped.setdefault(entry["category"], []).append(entry)
    blocks = [
        "<!-- Generated from the conformance and renderer suites' drift tables; do not edit by hand. Run\n"
        "`python -m tests.test_known_deviations` to regenerate it; tests/test_known_deviations.py fails if it\n"
        "drifts. -->\n\n"
        "# Known cross-tier deviations\n\n"
        "The accepted ways a backend legitimately differs from the others, consolidated from the four drift\n"
        "tables the conformance and renderer suites enforce (`NO_PORTABLE_CHANNELS`, `CANNOT_HIDE_AT_BUILD`,\n"
        "`NO_PORTABLE_CLASSIFICATION` and `UNDRAWN_KINDS`). Each is both-direction-guarded in its own suite, so\n"
        "a deviation cannot outlive the defect it excuses; this is the single reviewable list of all of them."
    ]
    for category, heading, description in _CATEGORIES:
        rows = grouped.get(category)
        if not rows:
            continue
        wrapped_description = textwrap.fill(
            description, width=118, break_long_words=False, break_on_hyphens=False
        )
        blocks.append(
            f"## {heading}\n\n{wrapped_description}\n\n"
            + "\n".join(_bullet(entry) for entry in rows)
        )
    return "\n\n".join(blocks).rstrip() + "\n"


def test_the_known_deviations_allowlist_is_current():
    """The ratchet: the committed allowlist must equal what the live drift tables render.

    Test scenario:
        Rebuild the allowlist from the four drift tables and compare it to the committed
        ``known_deviations.md``. An accepted deviation added or removed in any table with no regenerate fails
        here with the diff inline — so the one consolidated list cannot fall out of step with the tables that
        enforce the deviations.
    """
    assert_matches_committed(
        render_allowlist(),
        ALLOWLIST_PATH,
        what="known-deviations allowlist",
        regenerate="python -m tests.test_known_deviations",
    )


def test_render_allowlist_skips_a_category_with_no_live_rows(monkeypatch):
    """A category whose drift tables yield no live rows contributes no section.

    Test scenario:
        ``render_allowlist`` emits one section per category in ``_CATEGORIES`` that has at least one entry; a
        category with none is skipped. With the live tables all four categories are populated, so drive the
        skip directly by monkeypatching :func:`collect_known_deviations` to return rows for only one category,
        then confirm the populated category's heading renders and the others' do not.
    """
    monkeypatch.setattr(
        "tests.test_known_deviations.collect_known_deviations",
        lambda: [
            {
                "category": "no_portable_channels",
                "backend": "web",
                "subject": "",
                "reason": "r",
            }
        ],
    )
    page = render_allowlist()
    assert "## No portable style channels" in page, (
        f"the populated category should render:\n{page}"
    )
    assert "## No portable classification" not in page, (
        f"a category with no live rows should be skipped:\n{page}"
    )


if __name__ == "__main__":  # pragma: no cover
    # regenerate the allowlist after a deliberate drift-table change
    ALLOWLIST_PATH.write_text(render_allowlist(), encoding="utf-8")
    print(f"wrote {ALLOWLIST_PATH}")
