"""One committed snapshot of the public API surface, diffed on every run — the first U-5 ratchet.

The contract and the capability declarations are each guarded today (``tests/test_contract_names.py``,
``tests/base/test_capabilities.py``, ``tests/test_package_exports.py``), but each holds its own slice against an
``EXPECTED`` list written inline in that test. This is the **consolidated** guard: the whole engine-free public
surface — top-level exports, the Core/Tier-2 contract (names, keywords, call shape), what keywords each backend
honours, and each tier's full :class:`~digitalearth.base.capabilities.Capabilities` — captured in one committed
artifact (:data:`SNAPSHOT_PATH`) and compared as one unit. Any addition, removal, rename, keyword change or
capability change anywhere in that surface shows up as a single reviewable diff in the pull request, so a public
change is a deliberate, reviewed snapshot update rather than something that slips through unnoticed.

**It is engine-free on purpose.** Every source it reads — ``digitalearth.__all__``, ``base.contract``,
``api.BACKEND_CAPABILITIES`` and each tier's ``capabilities.CAPABILITIES`` — imports without MapLibre, HoloViz or
PyVista, so this runs (and ratchets) in the lean ``dev`` matrix on every OS, not only where an extra is installed.

**To change the API on purpose:** make the change, run ``python -m tests.test_api_snapshot`` to rewrite
:data:`SNAPSHOT_PATH`, and commit the diff alongside the change. An *unintended* drift fails the test with the
diff inline.
"""

import json
from pathlib import Path
from typing import Any, Dict

from digitalearth import __all__ as TOP_LEVEL_EXPORTS
from digitalearth.api import BACKEND_CAPABILITIES
from digitalearth.base import contract
from tests.base.test_map_conformance import ALL_TIERS
from tests.capability_surface import TIER_CAPABILITY_MODULES, tier_capabilities
from tests.ratchet import assert_matches_committed
from tests.test_support_matrix import BACKENDS as MATRIX_BACKENDS

#: The committed snapshot, beside this test. Regenerated by running this file as a script.
SNAPSHOT_PATH = Path(__file__).with_name("api_snapshot.json")


def _method(method: contract.Method) -> Dict[str, Any]:
    """Reduce one contract :class:`~digitalearth.base.contract.Method` to its snapshot form.

    Args:
        method: The contract method.

    Returns:
        Its name, sorted keywords, return kind, and declared call shape — the call surface a caller sees.
    """
    return {
        "name": method.name,
        "keywords": sorted(method.keywords),
        "returns": method.returns,
        "first_argument": method.first_argument,
        "sequence_order": list(method.sequence_order)
        if method.sequence_order is not None
        else None,
        "builds_in": method.builds_in,
    }


def _capability_shape(caps: Dict[str, Any]) -> Dict[str, Any]:
    """Return a tier's capabilities as API *shape* — its ``absent`` prose reasons reduced to sorted names.

    The snapshot tracks what the API is, not the justification for what a backend omits. A tier's ``absent``
    reasons are ratcheted (as wrapped prose) by the support matrix (``tests/test_support_matrix.py``); the
    known-deviations allowlist (``tests/test_known_deviations.py``) consolidates different data — the conformance
    drift tables — not ``absent``. Keeping the reasons out here also stops a reworded reason from reading as an
    API change, and keeps every snapshot line short.

    Args:
        caps: A tier's :meth:`~digitalearth.base.capabilities.Capabilities.to_dict`.

    Returns:
        The same dict with ``absent`` as a sorted list of the omitted names, reasons dropped.
    """
    return {**caps, "absent": sorted(caps["absent"])}


def public_api_surface() -> Dict[str, Any]:
    """Build the engine-free public API surface as plain, sorted, JSON-able data.

    Returns:
        The top-level exports, the Core/Tier-2 contract (in declaration order), which methods each backend has
        ``PENDING``, the per-backend honoured keywords, and each tier's capability shape — all deterministic so
        two machines produce byte-identical output. Prose is excluded, because it is not API shape: a tier's
        ``absent`` reasons are ratcheted (as wrapped text) by the support matrix, while ``contract.PENDING``
        reasons and ``Method.doc`` are ratcheted by no U-5 artifact (the deviations allowlist consolidates the
        conformance drift tables, which are different data).
    """
    return {
        "top_level_exports": sorted(TOP_LEVEL_EXPORTS),
        "contract": {
            "core": [_method(method) for method in contract.CORE],
            "tier2": [_method(method) for method in contract.TIER2],
            "pending": {
                backend: sorted(contract.PENDING[backend])
                for backend in sorted(contract.PENDING)
            },
        },
        "backend_keyword_capabilities": {
            backend: sorted(BACKEND_CAPABILITIES[backend])
            for backend in sorted(BACKEND_CAPABILITIES)
        },
        "backend_capabilities": {
            backend: _capability_shape(tier_capabilities(backend))
            for backend in sorted(TIER_CAPABILITY_MODULES)
        },
    }


def _serialise(surface: Dict[str, Any]) -> str:
    """Serialise the surface deterministically (sorted keys, trailing newline), so a diff is stable."""
    return json.dumps(surface, indent=2, sort_keys=True) + "\n"


def test_the_public_api_matches_the_committed_snapshot():
    """The ratchet: the live public surface must equal the committed snapshot, or the diff is shown.

    Test scenario:
        Rebuild the surface from the live declarations and compare it, serialised, to the committed
        ``api_snapshot.json``. A match means nothing public moved; a mismatch is either an intended change
        whose snapshot was not regenerated, or an unintended public-API change — both of which a reviewer
        should see, so the failure carries the unified diff rather than an opaque "dicts differ".
    """
    assert_matches_committed(
        _serialise(public_api_surface()),
        SNAPSHOT_PATH,
        what="public API surface",
        regenerate="python -m tests.test_api_snapshot",
    )


def test_method_keeps_an_empty_sequence_order_distinct_from_an_undeclared_one():
    """``_method`` snapshots an empty ``sequence_order=()`` as ``[]``, not as ``null``.

    Test scenario:
        ``()`` means "declared, no components"; ``None`` means "ordering undeclared". Both are falsy, so a
        truthiness test would map them to the same ``null`` and lose the distinction. No current contract
        method has ``()``, so this guards the reduction against a future one.
    """
    empty = contract.Method(name="x", doc="d", sequence_order=())
    undeclared = contract.Method(name="y", doc="d")
    assert _method(empty)["sequence_order"] == [], (
        f"an empty sequence_order should snapshot as [], got {_method(empty)['sequence_order']!r}"
    )
    assert _method(undeclared)["sequence_order"] is None, (
        f"an undeclared sequence_order should snapshot as None, got {_method(undeclared)['sequence_order']!r}"
    )


def test_the_snapshot_and_matrix_cover_every_tier():
    """Every tier the package ships is in the snapshot, the support matrix and ``BACKEND_CAPABILITIES``.

    Test scenario:
        The snapshot and the support matrix iterate hand-written tier enumerations
        (:data:`~tests.capability_surface.TIER_CAPABILITY_MODULES`, :data:`~tests.test_support_matrix.BACKENDS`,
        and ``api.BACKEND_CAPABILITIES``). The conformance suite instead *discovers* the shipped tiers from
        ``src/digitalearth/*/capabilities.py`` (:data:`~tests.base.test_map_conformance.ALL_TIERS`), because a
        hand-written tier list goes stale in silence when a tier is added (#324 / R2-M8) — the snapshot and
        matrix would simply omit the new tier with every ratchet still green. This ties the three enumerations
        back to that discovery: a newly-shipped tier that was not added to them fails here instead.
    """
    shipped = set(ALL_TIERS)
    assert set(TIER_CAPABILITY_MODULES) == shipped, (
        f"TIER_CAPABILITY_MODULES {sorted(TIER_CAPABILITY_MODULES)} != shipped tiers {sorted(shipped)}"
    )
    assert set(MATRIX_BACKENDS) == shipped, (
        f"the support matrix's BACKENDS {sorted(MATRIX_BACKENDS)} != shipped tiers {sorted(shipped)}"
    )
    assert set(BACKEND_CAPABILITIES) == shipped, (
        f"BACKEND_CAPABILITIES keys {sorted(BACKEND_CAPABILITIES)} != shipped tiers {sorted(shipped)}"
    )


if __name__ == "__main__":  # pragma: no cover
    # regenerate the committed snapshot after a deliberate API change
    SNAPSHOT_PATH.write_text(_serialise(public_api_surface()), encoding="utf-8")
    print(f"wrote {SNAPSHOT_PATH}")
